services:
  rss_bot:
    build: .
    container_name: rss_discord_bot
    restart: unless-stopped

    env_file:
      - .env

    environment:
      - SUMMARIZE_MAX_CALLS=10
      - SUMMARIZE_INTERVAL=300
      - SUMMARIZE_TIMEOUT=300
      - ARTICLE_TIMEOUT=30
      - FEED_TIMEOUT=10
      - TZ=Asia/Tokyo   # 追加（tzdataインストール済みの場合有効）

    volumes:
      - ./data:/app/data
      - ./feeds.json:/app/feeds.json:ro   # フィード設定ファイル
      - /etc/localtime:/etc/localtime:ro   # ホストの時刻設定を共有
      - /etc/timezone:/etc/timezone:ro     # ホストのタイムゾーンを共有

    labels:
      - "homepage.name=RSS Summarizer"
      - "homepage.group=Bot"
      - "homepage.href=https://github.com/kichinosukey/rss-summarizer-lm"
      - "homepage.icon=https://upload.wikimedia.org/wikipedia/en/thumb/4/43/Feed-icon.svg/256px-Feed-icon.svg.png"